import type { Metadata } from "next";
// 1. Import Roboto_Flex
import { Geist, Geist_Mono, Roboto_Flex } from "next/font/google"; 
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// 2. Configure Roboto Flex
const robotoFlex = Roboto_Flex({
  subsets: ["latin"],
  variable: "--font-roboto-flex", // This defines the CSS variable name
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* 3. Add robotoFlex.variable to the className string */}
      <body className={`${geistSans.variable} ${geistMono.variable} ${robotoFlex.variable} antialiased`}>
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}